name: Publish @trycua/computer to npm

on:
  push:
    tags:
      - "computer-v*"

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ./libs/typescript/computer
        run: pnpm install --frozen-lockfile

      - name: Build package
        working-directory: ./libs/typescript/computer
        run: pnpm run build --if-present

      - name: Publish to npm
        working-directory: ./libs/typescript/computer
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
